apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: telegraf
  name: telegraf
  namespace: monitoring
data:
  cluster_name: sumo-eu-central-1a
  telegraf.conf: |
    [global_tags]
      product = "${CLUSTER_NAME}"
      environment = "production"
    [agent]
      hostname = "$HOSTNAME"

    # INPUTS
    [[inputs.net]]
      interfaces = ["eth0","eth1"]
    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false
      report_active = false
    [[inputs.disk]]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]
    [[inputs.diskio]]
    [[inputs.kernel]]
    [[inputs.mem]]
    [[inputs.processes]]
    [[inputs.swap]]
    [[inputs.system]]
    [[inputs.docker]]
      endpoint = "unix:///var/run/docker.sock"

    # Container level metrics
    [[inputs.prometheus]]
    urls = ["https://${HOST_IP}:10250/metrics/cadvisor"]
      bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      insecure_skip_verify = true
      interval = "60s"

    # OUTPUTS
    [[outputs.influxdb]]
      urls = ["${INFLUX_URL}"]
      database = "${INFLUX_DB}"
      timeout  = "15s"
      username = "${INFLUX_USER}"
      password = "${INFLUX_PW}"
